-- RAW table definitions: all columns as VARCHAR to support Keboola ingestion
-- Run this in a specific candidate RAW schema context, e.g.:
--   USE DATABASE ETL_INTERVIEW;
--   USE SCHEMA C01_RAW;

CREATE OR REPLACE TABLE DIM_CUSTOMER (
  CUSTOMER_ID VARCHAR,
  NAME VARCHAR,
  SEGMENT VARCHAR,
  REGION VARCHAR,
  LOAD_DATE VARCHAR,
  UPDATE_DATE VARCHAR
);

CREATE OR REPLACE TABLE DIM_CARRIER (
  CARRIER_ID VARCHAR,
  NAME VARCHAR,
  MODE VARCHAR,
  MC_NUMBER VARCHAR,
  SCORE_TIER VARCHAR,
  LOAD_DATE VARCHAR,
  UPDATE_DATE VARCHAR
);

CREATE OR REPLACE TABLE DIM_EQUIPMENT (
  EQUIPMENT_ID VARCHAR,
  TYPE VARCHAR,
  CAPACITY_LBS VARCHAR,
  LOAD_DATE VARCHAR,
  UPDATE_DATE VARCHAR
);

CREATE OR REPLACE TABLE DIM_LOCATION (
  LOC_ID VARCHAR,
  NAME VARCHAR,
  CITY VARCHAR,
  STATE VARCHAR,
  COUNTRY VARCHAR,
  TIMEZONE VARCHAR,
  TYPE VARCHAR,
  LOAD_DATE VARCHAR,
  UPDATE_DATE VARCHAR
);

CREATE OR REPLACE TABLE DIM_LANE (
  LANE_ID VARCHAR,
  ORIGIN_LOC_ID VARCHAR,
  DEST_LOC_ID VARCHAR,
  STANDARD_MILES VARCHAR,
  STD_TRANSIT_DAYS VARCHAR,
  LOAD_DATE VARCHAR,
  UPDATE_DATE VARCHAR
);

CREATE OR REPLACE TABLE DIM_DATE (
  DATE_KEY VARCHAR,
  DATE VARCHAR,
  YEAR VARCHAR,
  QUARTER VARCHAR,
  MONTH VARCHAR,
  WEEK VARCHAR,
  DOW VARCHAR,
  IS_WEEKEND VARCHAR,
  LOAD_DATE VARCHAR,
  UPDATE_DATE VARCHAR
);

CREATE OR REPLACE TABLE FACT_SHIPMENT (
  SHIPMENT_ID VARCHAR,
  LEG_ID VARCHAR,
  CUSTOMER_ID VARCHAR,
  CARRIER_ID VARCHAR,
  EQUIPMENT_ID VARCHAR,
  ORIGIN_LOC_ID VARCHAR,
  DEST_LOC_ID VARCHAR,
  LANE_ID VARCHAR,
  TENDER_TS VARCHAR,
  PICKUP_PLAN_TS VARCHAR,
  PICKUP_ACTUAL_TS VARCHAR,
  DELIVERY_PLAN_TS VARCHAR,
  DELIVERY_ACTUAL_TS VARCHAR,
  PLANNED_MILES VARCHAR,
  ACTUAL_MILES VARCHAR,
  PIECES VARCHAR,
  WEIGHT_LBS VARCHAR,
  CUBE VARCHAR,
  REVENUE VARCHAR,
  TOTAL_COST VARCHAR,
  FUEL_SURCHARGE VARCHAR,
  ACCESSORIAL_COST VARCHAR,
  STATUS VARCHAR,
  ISDELIVEREDONTIME VARCHAR,
  ISINFULL VARCHAR,
  ISOTIF VARCHAR,
  CANCEL_FLAG VARCHAR,
  LOAD_DATE VARCHAR,
  UPDATE_DATE VARCHAR
);

CREATE OR REPLACE TABLE FACT_EVENT (
  SHIPMENT_ID VARCHAR,
  EVENT_SEQ VARCHAR,
  EVENT_TYPE VARCHAR,
  EVENT_TS VARCHAR,
  FACILITY_LOC_ID VARCHAR,
  NOTES VARCHAR,
  LOAD_DATE VARCHAR,
  UPDATE_DATE VARCHAR
);

CREATE OR REPLACE TABLE FACT_COST (
  SHIPMENT_ID VARCHAR,
  COST_TYPE VARCHAR,
  CALC_METHOD VARCHAR,
  RATE_REF VARCHAR,
  COST_AMOUNT VARCHAR,
  CURRENCY VARCHAR,
  LOAD_DATE VARCHAR,
  UPDATE_DATE VARCHAR
);

