-- Create application role and Keboola service user (no secrets embedded)
-- Replace placeholders via scripts/setup_snowflake_option_a.sh or manually before running.

-- Context
USE WAREHOUSE IDENTIFIER('LOGISTICS_WH');
USE DATABASE IDENTIFIER('LOGISTICS_DB');

-- App role
CREATE ROLE IF NOT EXISTS IDENTIFIER('LOGISTICS_APP_ROLE');

-- Grants: warehouse, database, schemas
GRANT USAGE ON WAREHOUSE IDENTIFIER('LOGISTICS_WH') TO ROLE IDENTIFIER('LOGISTICS_APP_ROLE');
GRANT USAGE ON DATABASE IDENTIFIER('LOGISTICS_DB') TO ROLE IDENTIFIER('LOGISTICS_APP_ROLE');
GRANT USAGE ON SCHEMA IDENTIFIER('STG') TO ROLE IDENTIFIER('LOGISTICS_APP_ROLE');
GRANT USAGE ON SCHEMA IDENTIFIER('EDW') TO ROLE IDENTIFIER('LOGISTICS_APP_ROLE');

-- STG privileges (Writer)
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA IDENTIFIER('STG') TO ROLE IDENTIFIER('LOGISTICS_APP_ROLE');
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA IDENTIFIER('STG') TO ROLE IDENTIFIER('LOGISTICS_APP_ROLE');
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA IDENTIFIER('STG') TO ROLE IDENTIFIER('LOGISTICS_APP_ROLE');

-- EDW privileges (Transform)
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA IDENTIFIER('EDW') TO ROLE IDENTIFIER('LOGISTICS_APP_ROLE');
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA IDENTIFIER('EDW') TO ROLE IDENTIFIER('LOGISTICS_APP_ROLE');
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA IDENTIFIER('EDW') TO ROLE IDENTIFIER('LOGISTICS_APP_ROLE');

-- Service user for Keboola (no password set here)
CREATE USER IF NOT EXISTS IDENTIFIER('KEBOOLA_LOGISTICS_USER')
  DEFAULT_ROLE = IDENTIFIER('LOGISTICS_APP_ROLE')
  DEFAULT_WAREHOUSE = IDENTIFIER('LOGISTICS_WH')
  DEFAULT_NAMESPACE = LOGISTICS_DB.STG
  MUST_CHANGE_PASSWORD = TRUE
  COMMENT = 'Keboola Writer/Transform user for Logistics project';

GRANT ROLE IDENTIFIER('LOGISTICS_APP_ROLE') TO USER IDENTIFIER('KEBOOLA_LOGISTICS_USER');

-- After creation, an ACCOUNTADMIN should set a password or keypair for KEBOOLA_LOGISTICS_USER:
--   ALTER USER IDENTIFIER('KEBOOLA_LOGISTICS_USER') SET PASSWORD = '<STRONG_PASSWORD>'; -- run outside of version control
-- Or configure RSA keypair auth:
--   ALTER USER IDENTIFIER('KEBOOLA_LOGISTICS_USER') SET RSA_PUBLIC_KEY = '<PEM_BASE64>';  
