-- Replace placeholders before executing.
-- Account: <SNOWFLAKE_ACCOUNT>
-- User: <USER>
-- Role: <ROLE>
-- Warehouse: LOGISTICS_WH
-- Database: LOGISTICS_DB
-- Schemas: STG, EDW

-- Roles and Grants (informational; adapt to your org)
-- CREATE ROLE IF NOT EXISTS <ROLE>;
-- GRANT ROLE <ROLE> TO USER <USER>;

-- Warehouse
CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER('LOGISTICS_WH')
  WITH WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 120
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

-- Database and Schemas
CREATE DATABASE IF NOT EXISTS IDENTIFIER('LOGISTICS_DB');
USE DATABASE IDENTIFIER('LOGISTICS_DB');
CREATE SCHEMA IF NOT EXISTS IDENTIFIER('STG');
CREATE SCHEMA IF NOT EXISTS IDENTIFIER('EDW');

-- File formats
USE SCHEMA IDENTIFIER('STG');
CREATE OR REPLACE FILE FORMAT CSV_FMT
  TYPE = 'CSV'
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  EMPTY_FIELD_AS_NULL = TRUE
  NULL_IF = ('', 'NULL');

-- Example grants (restrict as needed)
-- GRANT USAGE ON WAREHOUSE IDENTIFIER('LOGISTICS_WH') TO ROLE IDENTIFIER('<ROLE>');
-- GRANT USAGE ON DATABASE IDENTIFIER('LOGISTICS_DB') TO ROLE IDENTIFIER('<ROLE>');
-- GRANT USAGE ON SCHEMA IDENTIFIER('LOGISTICS_DB').IDENTIFIER('STG') TO ROLE IDENTIFIER('<ROLE>');
-- GRANT USAGE ON SCHEMA IDENTIFIER('LOGISTICS_DB').IDENTIFIER('EDW') TO ROLE IDENTIFIER('<ROLE>');
-- GRANT CREATE TABLE, CREATE STAGE, CREATE PIPE ON SCHEMA IDENTIFIER('LOGISTICS_DB').IDENTIFIER('STG') TO ROLE IDENTIFIER('<ROLE>');
-- GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA IDENTIFIER('LOGISTICS_DB').IDENTIFIER('EDW') TO ROLE IDENTIFIER('<ROLE>');
