-- Create application role and Keboola service user (no secrets embedded)
-- Replace placeholders via scripts/setup_snowflake_option_a.sh or manually before running.

-- Context
USE WAREHOUSE IDENTIFIER('<WAREHOUSE>');
USE DATABASE IDENTIFIER('<DATABASE>');

-- App role
CREATE ROLE IF NOT EXISTS IDENTIFIER('<APP_ROLE>');

-- Grants: warehouse, database, schemas
GRANT USAGE ON WAREHOUSE IDENTIFIER('<WAREHOUSE>') TO ROLE IDENTIFIER('<APP_ROLE>');
GRANT USAGE ON DATABASE IDENTIFIER('<DATABASE>') TO ROLE IDENTIFIER('<APP_ROLE>');
GRANT USAGE ON SCHEMA IDENTIFIER('<STG_SCHEMA>') TO ROLE IDENTIFIER('<APP_ROLE>');
GRANT USAGE ON SCHEMA IDENTIFIER('<EDW_SCHEMA>') TO ROLE IDENTIFIER('<APP_ROLE>');

-- STG privileges (Writer)
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA IDENTIFIER('<STG_SCHEMA>') TO ROLE IDENTIFIER('<APP_ROLE>');
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA IDENTIFIER('<STG_SCHEMA>') TO ROLE IDENTIFIER('<APP_ROLE>');
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA IDENTIFIER('<STG_SCHEMA>') TO ROLE IDENTIFIER('<APP_ROLE>');

-- EDW privileges (Transform)
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA IDENTIFIER('<EDW_SCHEMA>') TO ROLE IDENTIFIER('<APP_ROLE>');
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA IDENTIFIER('<EDW_SCHEMA>') TO ROLE IDENTIFIER('<APP_ROLE>');
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA IDENTIFIER('<EDW_SCHEMA>') TO ROLE IDENTIFIER('<APP_ROLE>');

-- Service user for Keboola (no password set here)
CREATE USER IF NOT EXISTS IDENTIFIER('<APP_USER>')
  LOGIN_NAME = '<APP_USER>'
  DEFAULT_ROLE = '<APP_ROLE>'
  DEFAULT_WAREHOUSE = '<WAREHOUSE>'
  DEFAULT_NAMESPACE = '<DATABASE>.<STG_SCHEMA>'
  MUST_CHANGE_PASSWORD = TRUE
  COMMENT = 'Keboola Writer/Transform user for Logistics project';

GRANT ROLE IDENTIFIER('<APP_ROLE>') TO USER IDENTIFIER('<APP_USER>');

-- After creation, an ACCOUNTADMIN should set a password or keypair for <APP_USER>:
--   ALTER USER IDENTIFIER('<APP_USER>') SET PASSWORD = '<STRONG_PASSWORD>'; -- run outside of version control
-- Or configure RSA keypair auth:
--   ALTER USER IDENTIFIER('<APP_USER>') SET RSA_PUBLIC_KEY = '<PEM_BASE64>';  
