-- Replace placeholders before executing.
-- Account: <SNOWFLAKE_ACCOUNT>
-- User: <USER>
-- Role: <ROLE>
-- Warehouse: <WAREHOUSE>
-- Database: <DATABASE>
-- Schemas: <STG_SCHEMA>, <EDW_SCHEMA>

-- Roles and Grants (informational; adapt to your org)
-- CREATE ROLE IF NOT EXISTS <ROLE>;
-- GRANT ROLE <ROLE> TO USER <USER>;

-- Warehouse
CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER('<WAREHOUSE>')
  WITH WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 120
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

-- Database and Schemas
CREATE DATABASE IF NOT EXISTS IDENTIFIER('<DATABASE>');
CREATE SCHEMA IF NOT EXISTS IDENTIFIER('<DATABASE>').IDENTIFIER('<STG_SCHEMA>');
CREATE SCHEMA IF NOT EXISTS IDENTIFIER('<DATABASE>').IDENTIFIER('<EDW_SCHEMA>');

-- File formats
CREATE OR REPLACE FILE FORMAT IDENTIFIER('<DATABASE>').IDENTIFIER('<STG_SCHEMA>').CSV_FMT
  TYPE = 'CSV'
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  EMPTY_FIELD_AS_NULL = TRUE
  NULL_IF = ('', 'NULL');

-- Example grants (restrict as needed)
-- GRANT USAGE ON WAREHOUSE IDENTIFIER('<WAREHOUSE>') TO ROLE IDENTIFIER('<ROLE>');
-- GRANT USAGE ON DATABASE IDENTIFIER('<DATABASE>') TO ROLE IDENTIFIER('<ROLE>');
-- GRANT USAGE ON SCHEMA IDENTIFIER('<DATABASE>').IDENTIFIER('<STG_SCHEMA>') TO ROLE IDENTIFIER('<ROLE>');
-- GRANT USAGE ON SCHEMA IDENTIFIER('<DATABASE>').IDENTIFIER('<EDW_SCHEMA>') TO ROLE IDENTIFIER('<ROLE>');
-- GRANT CREATE TABLE, CREATE STAGE, CREATE PIPE ON SCHEMA IDENTIFIER('<DATABASE>').IDENTIFIER('<STG_SCHEMA>') TO ROLE IDENTIFIER('<ROLE>');
-- GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA IDENTIFIER('<DATABASE>').IDENTIFIER('<EDW_SCHEMA>') TO ROLE IDENTIFIER('<ROLE>');

