-- Example internal stage and COPY commands (edit placeholders and uncomment to use)

USE DATABASE IDENTIFIER('<DATABASE>');
USE SCHEMA IDENTIFIER('<DATABASE>').IDENTIFIER('<STG_SCHEMA>');

-- Internal stage for CSVs
CREATE OR REPLACE STAGE STAGE_CSV
  FILE_FORMAT = CSV_FMT;

-- To upload files:
-- Using SnowSQL or UI, PUT local files into the stage (if allowed):
-- PUT file://data/out/*.csv @STAGE_CSV AUTO_COMPRESS=TRUE;

-- Sample COPY commands (assumes files are named as generated)
-- COPY INTO DIM_CUSTOMER FROM @STAGE_CSV/DIM_CUSTOMER.csv.gz ON_ERROR='ABORT_STATEMENT';
-- COPY INTO DIM_CARRIER FROM @STAGE_CSV/DIM_CARRIER.csv.gz  ON_ERROR='ABORT_STATEMENT';
-- COPY INTO DIM_EQUIPMENT FROM @STAGE_CSV/DIM_EQUIPMENT.csv.gz ON_ERROR='ABORT_STATEMENT';
-- COPY INTO DIM_LOCATION FROM @STAGE_CSV/DIM_LOCATION.csv.gz  ON_ERROR='ABORT_STATEMENT';
-- COPY INTO DIM_LANE FROM @STAGE_CSV/DIM_LANE.csv.gz ON_ERROR='ABORT_STATEMENT';
-- COPY INTO DIM_DATE FROM @STAGE_CSV/DIM_DATE.csv.gz ON_ERROR='ABORT_STATEMENT';
-- COPY INTO FACT_SHIPMENT FROM @STAGE_CSV/FACT_SHIPMENT.csv.gz ON_ERROR='ABORT_STATEMENT';
-- COPY INTO FACT_EVENT FROM @STAGE_CSV/FACT_EVENT.csv.gz ON_ERROR='ABORT_STATEMENT';
-- COPY INTO FACT_COST FROM @STAGE_CSV/FACT_COST.csv.gz ON_ERROR='ABORT_STATEMENT';

-- Optional: Streams & Tasks (commented skeleton)
-- CREATE OR REPLACE STREAM STRM_FACT_SHIPMENT ON TABLE FACT_SHIPMENT;
-- CREATE OR REPLACE TASK TASK_EDW_MERGE
--   WAREHOUSE = '<WAREHOUSE>'
--   SCHEDULE = 'USING CRON 0 */1 * * * America/Los_Angeles'
-- AS
--   CALL <DATABASE>.<EDW_SCHEMA>.SP_MERGE_ALL(); -- Example stored proc (not included)
-- ALTER TASK TASK_EDW_MERGE RESUME;

