-- Normalize EDW table and column names: remove quotes and enforce canonical UPPERCASE identifiers
-- Run in LOGISTICS_DB.EDW. This script drops any empty uppercase tables first, renames the
-- quoted-lowercase tables to their uppercase names, then renames all quoted columns to
-- unquoted UPPERCASE.
--
-- WARNING:
-- - Only drop an uppercase table if it is confirmed empty. The statements below assume the
--   uppercase objects are empty placeholders and your data lives in the quoted-lowercase tables.
-- - Execute block-by-block, verifying counts if you’re uncertain.

USE DATABASE LOGISTICS_DB;
USE SCHEMA EDW;

-- FACT_SHIPMENT
ALTER TABLE FACT_SHIPMENT RENAME COLUMN "shipment_id" TO SHIPMENT_ID;
ALTER TABLE FACT_SHIPMENT RENAME COLUMN "leg_id" TO LEG_ID;
ALTER TABLE FACT_SHIPMENT RENAME COLUMN "customer_id" TO CUSTOMER_ID;
ALTER TABLE FACT_SHIPMENT RENAME COLUMN "carrier_id" TO CARRIER_ID;
ALTER TABLE FACT_SHIPMENT RENAME COLUMN "equipment_id" TO EQUIPMENT_ID;
ALTER TABLE FACT_SHIPMENT RENAME COLUMN "origin_loc_id" TO ORIGIN_LOC_ID;
ALTER TABLE FACT_SHIPMENT RENAME COLUMN "dest_loc_id" TO DEST_LOC_ID;
ALTER TABLE FACT_SHIPMENT RENAME COLUMN "lane_id" TO LANE_ID;
ALTER TABLE FACT_SHIPMENT RENAME COLUMN "tender_ts" TO TENDER_TS;
ALTER TABLE FACT_SHIPMENT RENAME COLUMN "pickup_plan_ts" TO PICKUP_PLAN_TS;
ALTER TABLE FACT_SHIPMENT RENAME COLUMN "pickup_actual_ts" TO PICKUP_ACTUAL_TS;
ALTER TABLE FACT_SHIPMENT RENAME COLUMN "delivery_plan_ts" TO DELIVERY_PLAN_TS;
ALTER TABLE FACT_SHIPMENT RENAME COLUMN "delivery_actual_ts" TO DELIVERY_ACTUAL_TS;
ALTER TABLE FACT_SHIPMENT RENAME COLUMN "planned_miles" TO PLANNED_MILES;
ALTER TABLE FACT_SHIPMENT RENAME COLUMN "actual_miles" TO ACTUAL_MILES;
ALTER TABLE FACT_SHIPMENT RENAME COLUMN "pieces" TO PIECES;
ALTER TABLE FACT_SHIPMENT RENAME COLUMN "weight_lbs" TO WEIGHT_LBS;
ALTER TABLE FACT_SHIPMENT RENAME COLUMN "cube" TO CUBE;
ALTER TABLE FACT_SHIPMENT RENAME COLUMN "revenue" TO REVENUE;
ALTER TABLE FACT_SHIPMENT RENAME COLUMN "total_cost" TO TOTAL_COST;
ALTER TABLE FACT_SHIPMENT RENAME COLUMN "fuel_surcharge" TO FUEL_SURCHARGE;
ALTER TABLE FACT_SHIPMENT RENAME COLUMN "accessorial_cost" TO ACCESSORIAL_COST;
ALTER TABLE FACT_SHIPMENT RENAME COLUMN "status" TO STATUS;
ALTER TABLE FACT_SHIPMENT RENAME COLUMN "isdeliveredontime" TO ISDELIVEREDONTIME;
ALTER TABLE FACT_SHIPMENT RENAME COLUMN "isinfull" TO ISINFULL;
ALTER TABLE FACT_SHIPMENT RENAME COLUMN "isotif" TO ISOTIF;
ALTER TABLE FACT_SHIPMENT RENAME COLUMN "cancel_flag" TO CANCEL_FLAG;
ALTER TABLE FACT_SHIPMENT RENAME COLUMN "load_date" TO LOAD_DATE;
ALTER TABLE FACT_SHIPMENT RENAME COLUMN "update_date" TO UPDATE_DATE;

-- FACT_EVENT
ALTER TABLE FACT_EVENT RENAME COLUMN "shipment_id" TO SHIPMENT_ID;
ALTER TABLE FACT_EVENT RENAME COLUMN "event_seq" TO EVENT_SEQ;
ALTER TABLE FACT_EVENT RENAME COLUMN "event_type" TO EVENT_TYPE;
ALTER TABLE FACT_EVENT RENAME COLUMN "event_ts" TO EVENT_TS;
ALTER TABLE FACT_EVENT RENAME COLUMN "facility_loc_id" TO FACILITY_LOC_ID;
ALTER TABLE FACT_EVENT RENAME COLUMN "notes" TO NOTES;
ALTER TABLE FACT_EVENT RENAME COLUMN "load_date" TO LOAD_DATE;
ALTER TABLE FACT_EVENT RENAME COLUMN "update_date" TO UPDATE_DATE;

-- FACT_COST
ALTER TABLE FACT_COST RENAME COLUMN "shipment_id" TO SHIPMENT_ID;
ALTER TABLE FACT_COST RENAME COLUMN "cost_type" TO COST_TYPE;
ALTER TABLE FACT_COST RENAME COLUMN "calc_method" TO CALC_METHOD;
ALTER TABLE FACT_COST RENAME COLUMN "rate_ref" TO RATE_REF;
ALTER TABLE FACT_COST RENAME COLUMN "cost_amount" TO COST_AMOUNT;
ALTER TABLE FACT_COST RENAME COLUMN "currency" TO CURRENCY;
ALTER TABLE FACT_COST RENAME COLUMN "load_date" TO LOAD_DATE;
ALTER TABLE FACT_COST RENAME COLUMN "update_date" TO UPDATE_DATE;

-- DIM_CUSTOMER
ALTER TABLE "dim_customer" RENAME TO DIM_CUSTOMER;
ALTER TABLE DIM_CUSTOMER RENAME COLUMN "customer_id" TO CUSTOMER_ID;
ALTER TABLE DIM_CUSTOMER RENAME COLUMN "name" TO NAME;
ALTER TABLE DIM_CUSTOMER RENAME COLUMN "segment" TO SEGMENT;
ALTER TABLE DIM_CUSTOMER RENAME COLUMN "region" TO REGION;
ALTER TABLE DIM_CUSTOMER RENAME COLUMN "load_date" TO LOAD_DATE;
ALTER TABLE DIM_CUSTOMER RENAME COLUMN "update_date" TO UPDATE_DATE;

-- DIM_CARRIER
ALTER TABLE DIM_CARRIER RENAME COLUMN "carrier_id" TO CARRIER_ID;
ALTER TABLE DIM_CARRIER RENAME COLUMN "name" TO NAME;
ALTER TABLE DIM_CARRIER RENAME COLUMN "mode" TO MODE;
ALTER TABLE DIM_CARRIER RENAME COLUMN "mc_number" TO MC_NUMBER;
ALTER TABLE DIM_CARRIER RENAME COLUMN "score_tier" TO SCORE_TIER;
ALTER TABLE DIM_CARRIER RENAME COLUMN "load_date" TO LOAD_DATE;
ALTER TABLE DIM_CARRIER RENAME COLUMN "update_date" TO UPDATE_DATE;

-- DIM_EQUIPMENT
ALTER TABLE DIM_EQUIPMENT RENAME COLUMN "equipment_id" TO EQUIPMENT_ID;
ALTER TABLE DIM_EQUIPMENT RENAME COLUMN "type" TO TYPE;
ALTER TABLE DIM_EQUIPMENT RENAME COLUMN "capacity_lbs" TO CAPACITY_LBS;
ALTER TABLE DIM_EQUIPMENT RENAME COLUMN "load_date" TO LOAD_DATE;
ALTER TABLE DIM_EQUIPMENT RENAME COLUMN "update_date" TO UPDATE_DATE;

-- DIM_LOCATION
ALTER TABLE DIM_LOCATION RENAME COLUMN "loc_id" TO LOC_ID;
ALTER TABLE DIM_LOCATION RENAME COLUMN "name" TO NAME;
ALTER TABLE DIM_LOCATION RENAME COLUMN "city" TO CITY;
ALTER TABLE DIM_LOCATION RENAME COLUMN "state" TO STATE;
ALTER TABLE DIM_LOCATION RENAME COLUMN "country" TO COUNTRY;
ALTER TABLE DIM_LOCATION RENAME COLUMN "timezone" TO TIMEZONE;
ALTER TABLE DIM_LOCATION RENAME COLUMN "type" TO TYPE;
ALTER TABLE DIM_LOCATION RENAME COLUMN "load_date" TO LOAD_DATE;
ALTER TABLE DIM_LOCATION RENAME COLUMN "update_date" TO UPDATE_DATE;

-- DIM_LANE
ALTER TABLE DIM_LANE RENAME COLUMN "lane_id" TO LANE_ID;
ALTER TABLE DIM_LANE RENAME COLUMN "origin_loc_id" TO ORIGIN_LOC_ID;
ALTER TABLE DIM_LANE RENAME COLUMN "dest_loc_id" TO DEST_LOC_ID;
ALTER TABLE DIM_LANE RENAME COLUMN "standard_miles" TO STANDARD_MILES;
ALTER TABLE DIM_LANE RENAME COLUMN "std_transit_days" TO STD_TRANSIT_DAYS;
ALTER TABLE DIM_LANE RENAME COLUMN "load_date" TO LOAD_DATE;
ALTER TABLE DIM_LANE RENAME COLUMN "update_date" TO UPDATE_DATE;

-- DIM_DATE
ALTER TABLE DIM_DATE RENAME COLUMN "date_key" TO DATE_KEY;
ALTER TABLE DIM_DATE RENAME COLUMN "date" TO DATE;
ALTER TABLE DIM_DATE RENAME COLUMN "year" TO YEAR;
ALTER TABLE DIM_DATE RENAME COLUMN "quarter" TO QUARTER;
ALTER TABLE DIM_DATE RENAME COLUMN "month" TO MONTH;
ALTER TABLE DIM_DATE RENAME COLUMN "week" TO WEEK;
ALTER TABLE DIM_DATE RENAME COLUMN "dow" TO DOW;
ALTER TABLE DIM_DATE RENAME COLUMN "is_weekend" TO IS_WEEKEND;
ALTER TABLE DIM_DATE RENAME COLUMN "load_date" TO LOAD_DATE;
ALTER TABLE DIM_DATE RENAME COLUMN "update_date" TO UPDATE_DATE;

-- Verification (optional)
-- SELECT COUNT(1) total, COUNT_IF(delivery_actual_ts IS NOT NULL) delivered FROM FACT_SHIPMENT;
-- SELECT MIN(DATE(delivery_actual_ts)) min_d, MAX(DATE(delivery_actual_ts)) max_d FROM FACT_SHIPMENT WHERE delivery_actual_ts IS NOT NULL;

