-- Create typed MODEL tables in your assigned schema
-- Edit Cxx to your candidate code (e.g., C07)

SET DB_NAME = 'ETL_INTERVIEW';
SET CAND = 'Cxx';  -- replace with your code
SET MODEL = $CAND || '_MODEL';

USE DATABASE IDENTIFIER($DB_NAME);
USE SCHEMA IDENTIFIER($MODEL);

-- Example DDLs (adjust types/keys as appropriate)
CREATE OR REPLACE TABLE DIM_CUSTOMER (
  CUSTOMER_ID INTEGER PRIMARY KEY,
  NAME VARCHAR,
  SEGMENT VARCHAR,
  REGION VARCHAR
);

CREATE OR REPLACE TABLE DIM_CARRIER (
  CARRIER_ID INTEGER PRIMARY KEY,
  NAME VARCHAR,
  MODE VARCHAR,
  MC_NUMBER VARCHAR,
  SCORE_TIER VARCHAR
);

CREATE OR REPLACE TABLE DIM_EQUIPMENT (
  EQUIPMENT_ID INTEGER PRIMARY KEY,
  TYPE VARCHAR,
  CAPACITY_LBS INTEGER
);

CREATE OR REPLACE TABLE DIM_LOCATION (
  LOC_ID INTEGER PRIMARY KEY,
  NAME VARCHAR,
  CITY VARCHAR,
  STATE VARCHAR,
  COUNTRY VARCHAR,
  TIMEZONE VARCHAR,
  TYPE VARCHAR
);

CREATE OR REPLACE TABLE DIM_LANE (
  LANE_ID INTEGER PRIMARY KEY,
  ORIGIN_LOC_ID INTEGER,
  DEST_LOC_ID INTEGER,
  STANDARD_MILES NUMBER(10,2),
  STD_TRANSIT_DAYS INTEGER
);

CREATE OR REPLACE TABLE DIM_DATE (
  DATE_KEY INTEGER PRIMARY KEY,
  DATE DATE,
  YEAR INTEGER,
  QUARTER INTEGER,
  MONTH INTEGER,
  WEEK INTEGER,
  DOW INTEGER,
  IS_WEEKEND BOOLEAN
);

CREATE OR REPLACE TABLE FACT_SHIPMENT (
  SHIPMENT_ID VARCHAR,
  LEG_ID INTEGER,
  CUSTOMER_ID INTEGER,
  CARRIER_ID INTEGER,
  EQUIPMENT_ID INTEGER,
  ORIGIN_LOC_ID INTEGER,
  DEST_LOC_ID INTEGER,
  LANE_ID INTEGER,
  TENDER_TS TIMESTAMP_NTZ,
  PICKUP_PLAN_TS TIMESTAMP_NTZ,
  PICKUP_ACTUAL_TS TIMESTAMP_NTZ,
  DELIVERY_PLAN_TS TIMESTAMP_NTZ,
  DELIVERY_ACTUAL_TS TIMESTAMP_NTZ,
  PLANNED_MILES NUMBER(10,2),
  ACTUAL_MILES NUMBER(10,2),
  PIECES INTEGER,
  WEIGHT_LBS NUMBER(10,2),
  CUBE NUMBER(10,2),
  REVENUE NUMBER(12,2),
  TOTAL_COST NUMBER(12,2),
  FUEL_SURCHARGE NUMBER(12,2),
  ACCESSORIAL_COST NUMBER(12,2),
  STATUS VARCHAR,
  ISDELIVEREDONTIME BOOLEAN,
  ISINFULL BOOLEAN,
  ISOTIF BOOLEAN,
  CANCEL_FLAG BOOLEAN,
  PRIMARY KEY (SHIPMENT_ID, LEG_ID)
);

CREATE OR REPLACE TABLE FACT_EVENT (
  SHIPMENT_ID VARCHAR,
  EVENT_SEQ INTEGER,
  EVENT_TYPE VARCHAR,
  EVENT_TS TIMESTAMP_NTZ,
  FACILITY_LOC_ID INTEGER,
  NOTES VARCHAR,
  PRIMARY KEY (SHIPMENT_ID, EVENT_SEQ)
);

CREATE OR REPLACE TABLE FACT_COST (
  SHIPMENT_ID VARCHAR,
  COST_TYPE VARCHAR,
  CALC_METHOD VARCHAR,
  RATE_REF VARCHAR,
  COST_AMOUNT NUMBER(12,2),
  CURRENCY VARCHAR
);

