-- Transform RAW (all VARCHAR) into typed MODEL tables
-- Edit Cxx to your candidate code (e.g., C07)

SET DB_NAME = 'ETL_INTERVIEW';
SET CAND = 'Cxx';  -- replace with your code
SET RAW = $CAND || '_RAW';
SET MODEL = $CAND || '_MODEL';

USE DATABASE IDENTIFIER($DB_NAME);

-- Example strategy: TRUNCATE+INSERT (idempotent). MERGE is also acceptable.

-- DIMs
TRUNCATE TABLE IDENTIFIER($MODEL).DIM_CUSTOMER;
INSERT INTO IDENTIFIER($MODEL).DIM_CUSTOMER
SELECT
  TO_NUMBER(CUSTOMER_ID), NAME, SEGMENT, REGION
FROM IDENTIFIER($RAW).DIM_CUSTOMER;

TRUNCATE TABLE IDENTIFIER($MODEL).DIM_CARRIER;
INSERT INTO IDENTIFIER($MODEL).DIM_CARRIER
SELECT
  TO_NUMBER(CARRIER_ID), NAME, MODE, MC_NUMBER, SCORE_TIER
FROM IDENTIFIER($RAW).DIM_CARRIER;

TRUNCATE TABLE IDENTIFIER($MODEL).DIM_EQUIPMENT;
INSERT INTO IDENTIFIER($MODEL).DIM_EQUIPMENT
SELECT
  TO_NUMBER(EQUIPMENT_ID), TYPE, TO_NUMBER(CAPACITY_LBS)
FROM IDENTIFIER($RAW).DIM_EQUIPMENT;

TRUNCATE TABLE IDENTIFIER($MODEL).DIM_LOCATION;
INSERT INTO IDENTIFIER($MODEL).DIM_LOCATION
SELECT
  TO_NUMBER(LOC_ID), NAME, CITY, STATE, COUNTRY, TIMEZONE, TYPE
FROM IDENTIFIER($RAW).DIM_LOCATION;

TRUNCATE TABLE IDENTIFIER($MODEL).DIM_LANE;
INSERT INTO IDENTIFIER($MODEL).DIM_LANE
SELECT
  TO_NUMBER(LANE_ID), TO_NUMBER(ORIGIN_LOC_ID), TO_NUMBER(DEST_LOC_ID),
  TO_NUMBER(STANDARD_MILES), TO_NUMBER(STD_TRANSIT_DAYS)
FROM IDENTIFIER($RAW).DIM_LANE;

TRUNCATE TABLE IDENTIFIER($MODEL).DIM_DATE;
INSERT INTO IDENTIFIER($MODEL).DIM_DATE
SELECT
  TO_NUMBER(DATE_KEY), TRY_TO_DATE(DATE), TO_NUMBER(YEAR), TO_NUMBER(QUARTER),
  TO_NUMBER(MONTH), TO_NUMBER(WEEK), TO_NUMBER(DOW),
  IFF(UPPER(IS_WEEKEND) IN ('1','T','TRUE','Y','YES'), TRUE,
      IFF(UPPER(IS_WEEKEND) IN ('0','F','FALSE','N','NO'), FALSE, NULL))
FROM IDENTIFIER($RAW).DIM_DATE;

-- FACTS
TRUNCATE TABLE IDENTIFIER($MODEL).FACT_SHIPMENT;
INSERT INTO IDENTIFIER($MODEL).FACT_SHIPMENT
SELECT
  SHIPMENT_ID,
  TO_NUMBER(LEG_ID),
  TO_NUMBER(CUSTOMER_ID),
  TO_NUMBER(CARRIER_ID),
  TO_NUMBER(EQUIPMENT_ID),
  TO_NUMBER(ORIGIN_LOC_ID),
  TO_NUMBER(DEST_LOC_ID),
  TO_NUMBER(LANE_ID),
  TRY_TO_TIMESTAMP_NTZ(TENDER_TS),
  TRY_TO_TIMESTAMP_NTZ(PICKUP_PLAN_TS),
  TRY_TO_TIMESTAMP_NTZ(PICKUP_ACTUAL_TS),
  TRY_TO_TIMESTAMP_NTZ(DELIVERY_PLAN_TS),
  TRY_TO_TIMESTAMP_NTZ(DELIVERY_ACTUAL_TS),
  TO_NUMBER(PLANNED_MILES),
  TO_NUMBER(ACTUAL_MILES),
  TO_NUMBER(PIECES),
  TO_NUMBER(WEIGHT_LBS),
  TO_NUMBER(CUBE),
  TO_NUMBER(REVENUE),
  TO_NUMBER(TOTAL_COST),
  TO_NUMBER(FUEL_SURCHARGE),
  TO_NUMBER(ACCESSORIAL_COST),
  STATUS,
  IFF(UPPER(ISDELIVEREDONTIME) IN ('1','T','TRUE','Y','YES'), TRUE, FALSE),
  IFF(UPPER(ISINFULL) IN ('1','T','TRUE','Y','YES'), TRUE, FALSE),
  IFF(UPPER(ISOTIF) IN ('1','T','TRUE','Y','YES'), TRUE, FALSE),
  IFF(UPPER(CANCEL_FLAG) IN ('1','T','TRUE','Y','YES'), TRUE, FALSE)
FROM IDENTIFIER($RAW).FACT_SHIPMENT;

TRUNCATE TABLE IDENTIFIER($MODEL).FACT_EVENT;
INSERT INTO IDENTIFIER($MODEL).FACT_EVENT
SELECT
  SHIPMENT_ID,
  TO_NUMBER(EVENT_SEQ),
  EVENT_TYPE,
  TRY_TO_TIMESTAMP_NTZ(EVENT_TS),
  TO_NUMBER(FACILITY_LOC_ID),
  NOTES
FROM IDENTIFIER($RAW).FACT_EVENT;

TRUNCATE TABLE IDENTIFIER($MODEL).FACT_COST;
INSERT INTO IDENTIFIER($MODEL).FACT_COST
SELECT
  SHIPMENT_ID, COST_TYPE, CALC_METHOD, RATE_REF, TO_NUMBER(COST_AMOUNT), CURRENCY
FROM IDENTIFIER($RAW).FACT_COST;

